#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not handle the case statement correctly, this might be a problem.
#   (2) The Java home directory may not be where you expect it. You should verify
#       the JAVA_HOME variable in your environment, or set it explicitly here.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in
    /*) app_path=$link ;;
    *) app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
export APP_HOME

# Detect the Java command to use when starting the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "error: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
        exit 1
    fi
else
    JAVACMD=java
    command -v java >/dev/null 2>&1 || { echo "error: JAVA_HOME is not defined and java could not be found" >&2 ; exit 1; }
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
    @)
        MAX_FD=$( ulimit -H -n ) || warn "Could not query maximum file descriptors on this system"
    ;;
    '')
        MAX_FD=262144
    ;;
    @*)
        eval "MAX_FD=\$${MAX_FD#@}"
    ;;
    *)
        warn "Could not parse the value of MAX_FD"
    ;;
    esac
    [ "$MAX_FD" ] && ulimit -n "$MAX_FD" || warn "Could not set maximum file descriptors"
fi

# Collect all arguments for the java command; all the others will be collected in JAVA_OPTS
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" by itself would be empty to avoid errors with using "command" below.
set +e
{ out=$( "$JAVACMD" "$@" ); } 2>&1
set -e

exitCode=$?

# Only stop if we got the bad exit code (the exception case).
if [ "$exitCode" != 0 ] ; then
    echo "$out"
    exit $exitCode
fi

# Exit successfully.
exit 0
