/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZahlungenRouteImport } from './routes/zahlungen'
import { Route as TermineRouteImport } from './routes/termine'
import { Route as SucheRouteImport } from './routes/suche'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EingangRouteImport } from './routes/eingang'
import { Route as IndexRouteImport } from './routes/index'

const ZahlungenRoute = ZahlungenRouteImport.update({
  id: '/zahlungen',
  path: '/zahlungen',
  getParentRoute: () => rootRouteImport,
} as any)
const TermineRoute = TermineRouteImport.update({
  id: '/termine',
  path: '/termine',
  getParentRoute: () => rootRouteImport,
} as any)
const SucheRoute = SucheRouteImport.update({
  id: '/suche',
  path: '/suche',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EingangRoute = EingangRouteImport.update({
  id: '/eingang',
  path: '/eingang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eingang': typeof EingangRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/suche': typeof SucheRoute
  '/termine': typeof TermineRoute
  '/zahlungen': typeof ZahlungenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eingang': typeof EingangRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/suche': typeof SucheRoute
  '/termine': typeof TermineRoute
  '/zahlungen': typeof ZahlungenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eingang': typeof EingangRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/suche': typeof SucheRoute
  '/termine': typeof TermineRoute
  '/zahlungen': typeof ZahlungenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eingang'
    | '/login'
    | '/register'
    | '/suche'
    | '/termine'
    | '/zahlungen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eingang'
    | '/login'
    | '/register'
    | '/suche'
    | '/termine'
    | '/zahlungen'
  id:
    | '__root__'
    | '/'
    | '/eingang'
    | '/login'
    | '/register'
    | '/suche'
    | '/termine'
    | '/zahlungen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EingangRoute: typeof EingangRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SucheRoute: typeof SucheRoute
  TermineRoute: typeof TermineRoute
  ZahlungenRoute: typeof ZahlungenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zahlungen': {
      id: '/zahlungen'
      path: '/zahlungen'
      fullPath: '/zahlungen'
      preLoaderRoute: typeof ZahlungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termine': {
      id: '/termine'
      path: '/termine'
      fullPath: '/termine'
      preLoaderRoute: typeof TermineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suche': {
      id: '/suche'
      path: '/suche'
      fullPath: '/suche'
      preLoaderRoute: typeof SucheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eingang': {
      id: '/eingang'
      path: '/eingang'
      fullPath: '/eingang'
      preLoaderRoute: typeof EingangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EingangRoute: EingangRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SucheRoute: SucheRoute,
  TermineRoute: TermineRoute,
  ZahlungenRoute: ZahlungenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
